"""
PDF Exporter module for ComicCraft.
Generates professional printable and downloadable comic PDFs.
Section 12 Requirement.
"""

import os
import time
from pathlib import Path
from fpdf import FPDF
from app.config import EXPORTS_DIR, BASE_DIR
from app.models import ComicResponse


class ComicPDF(FPDF):
    """Custom FPDF class tailored for comic books."""

    def __init__(self, comic_title: str):
        super().__init__(orientation="P", unit="mm", format="A4")
        self.comic_title = comic_title
        self.set_auto_page_break(auto=True, margin=15)

    def header(self):
        # Comic Header banner
        self.set_fill_color(250, 204, 21)  # Yellow-400
        self.rect(0, 0, 210, 14, "F")
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(17, 24, 39)
        self.set_xy(10, 3)
        self.cell(190, 8, f"COMICCRAFT  |  {self.comic_title.upper()}", align="L")
        self.ln(12)

    def footer(self):
        self.set_y(-12)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(107, 114, 128)
        self.cell(0, 10, f"Page {self.page_no()} of {{nb}}  |  Generated by ComicCraft AI", align="C")


def save_pdf(comic: ComicResponse) -> str:
    """
    Assembles all 5 panels into a clean, multi-page comic book PDF.
    Returns relative URL path under /static/exports/.
    """
    timestamp = time.strftime("%Y%m%d_%H%M%S")
    filename = f"comic_{timestamp}.pdf"
    filepath = EXPORTS_DIR / filename

    pdf = ComicPDF(comic.story_title)
    pdf.alias_nb_pages()

    # Cover Page / Header
    pdf.add_page()
    pdf.set_fill_color(30, 27, 75)  # Dark Indigo
    pdf.rect(10, 20, 190, 48, "F")
    pdf.set_draw_color(250, 204, 21)
    pdf.set_line_width(1.5)
    pdf.rect(12, 22, 186, 44, "D")

    # Title & Credits
    pdf.set_font("Helvetica", "B", 22)
    pdf.set_text_color(254, 240, 138)
    pdf.set_xy(15, 26)
    # Sanitize title for Latin-1/Unicode in standard FPDF
    safe_title = comic.story_title.encode("latin-1", "replace").decode("latin-1")
    pdf.cell(180, 12, safe_title, align="C")

    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(255, 255, 255)
    pdf.set_xy(15, 42)
    safe_char = comic.character_profile.name.encode("latin-1", "replace").decode("latin-1")
    pdf.cell(180, 8, f"Starring: {safe_char}  *  Setting: {comic.setting}  *  Style: {comic.art_style}", align="C")

    pdf.set_xy(10, 75)

    # Render each panel (Panels 1 and 2 on Page 1; Panels 3 and 4 on Page 2; Panel 5 on Page 3)
    for i, panel in enumerate(comic.panels):
        # Page layout management: Panel 1 & 2 on page 1, 3 & 4 on page 2, 5 on page 3
        if i == 2 or i == 4:
            pdf.add_page()
            pdf.set_xy(10, 22)

        # Panel Header Box
        pdf.set_fill_color(254, 240, 138)  # Vintage Yellow
        pdf.set_draw_color(17, 24, 39)
        pdf.set_line_width(0.8)
        current_y = pdf.get_y()
        pdf.rect(10, current_y, 190, 8, "FD")

        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(17, 24, 39)
        safe_panel_title = f"PANEL {panel.panel_number}: {panel.title.upper()} [{panel.mood.upper()}]"
        safe_panel_title = safe_panel_title.encode("latin-1", "replace").decode("latin-1")
        pdf.set_xy(12, current_y + 1)
        pdf.cell(186, 6, safe_panel_title, align="L")

        pdf.ln(9)
        image_y = pdf.get_y()

        # Insert Panel Artwork
        image_placed = False
        if panel.image_url:
            # Check if it's a local file in static/panels/
            rel_path = panel.image_url.lstrip("/")
            local_file = BASE_DIR / rel_path
            if local_file.exists() and local_file.is_file():
                try:
                    pdf.image(str(local_file), x=10, y=image_y, w=90, h=65)
                    image_placed = True
                except Exception as img_err:
                    pdf.set_xy(10, image_y)
                    pdf.cell(90, 65, "[Comic Illustration]", border=1, align="C")
                    image_placed = True

        if not image_placed:
            pdf.set_xy(10, image_y)
            pdf.set_fill_color(243, 244, 246)
            pdf.rect(10, image_y, 90, 65, "FD")
            pdf.set_font("Helvetica", "I", 9)
            pdf.set_text_color(107, 114, 128)
            pdf.set_xy(10, image_y + 25)
            pdf.cell(90, 10, f"Panel {panel.panel_number} Visual Art", align="C")

        # Caption & Dialogue Column on the right side
        text_x = 105
        text_y = image_y
        pdf.set_xy(text_x, text_y)

        # Comic Caption Box
        pdf.set_fill_color(255, 251, 235)  # Amber-50
        pdf.set_draw_color(245, 158, 11)   # Amber-500
        pdf.set_line_width(0.5)
        pdf.rect(text_x, text_y, 95, 18, "FD")
        pdf.set_xy(text_x + 2, text_y + 1)
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_text_color(180, 83, 9)
        safe_caption = panel.caption.encode("latin-1", "replace").decode("latin-1")
        pdf.cell(91, 4, safe_caption[:45], ln=True)

        pdf.set_font("Helvetica", "I", 8)
        pdf.set_text_color(31, 41, 55)
        safe_narration = panel.narration.encode("latin-1", "replace").decode("latin-1")
        pdf.set_xy(text_x + 2, text_y + 5)
        pdf.multi_cell(91, 3.8, safe_narration[:130])

        # Dialogues
        dialogue_y = text_y + 21
        pdf.set_xy(text_x, dialogue_y)
        for d in panel.dialogue[:3]:
            pdf.set_fill_color(255, 255, 255)
            pdf.set_draw_color(17, 24, 39)
            pdf.set_line_width(0.4)
            char_name = d.character.encode("latin-1", "replace").decode("latin-1")
            speech = d.text.encode("latin-1", "replace").decode("latin-1")

            pdf.set_font("Helvetica", "B", 8)
            pdf.set_text_color(220, 38, 38)
            pdf.cell(95, 4, f"{char_name}:", ln=True)

            pdf.set_font("Helvetica", "", 8)
            pdf.set_text_color(17, 24, 39)
            pdf.multi_cell(95, 3.8, f'"{speech}"')
            pdf.ln(1)

        # Move to next panel
        pdf.set_y(image_y + 70)
        pdf.ln(4)

    pdf.output(str(filepath))
    return f"/static/exports/{filename}"
